### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KettleLake**
Hello Will, I hope you are having a good day. I have made a few small suggestions about how you could improve the grammatical structure of your GitHub's README.md file. Your project looks interesting and it intuitively makes sense to bring awareness to the user of where they may stutter and if there is a pattern to focus there attention on it to solve the issue there. I wish you the best of luck

### CODE REVIEW

**Comment by loneicewolf** [comment]
@KettleLake  Hello!  thanks for this PR, I will check it out !
Really, thanks a lot for trying to improve, writing is my biggest problem(I can't write clearly) so, looking trough it right now!

**Review by loneicewolf — APPROVED** [review]
- it will (or, more specifically `it's goal is to`) Help those who stutters, Like myself.
- it will (or, more specifically `it's goal is to`) help those who stutters, like myself.

# Approved! ✅

**Review by loneicewolf — APPROVED** [review]
-  Note! Grammar has never been my strong front, so please - if you spot any(any!) error (not only grammar) please point it out!
-  Note! Grammar has never been my strong suit, so please - if you spot any(any!) error (not only grammar) please point it out!

# Approved! ✅

**Comment by loneicewolf** [comment]
Thanks a lot for the contribution! really, It means *so much*, have a GREAT week and a AMAZING day at you! 

//Will.

**Comment by KettleLake** [comment]
I am glad to have helped. Have an amazing **### YEAR**!!!

**Pull request merged**
